name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Cargo: test, clippy, fmt"
        run: |
          rustup toolchain install nightly --profile minimal -c clippy rustfmt
          cargo +nightly test
          cargo +nightly clippy -- -D warnings
          cargo +nightly fmt -- --check
